# Generated by Django 5.2.2 on 2025-06-09 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pdf', models.FileField(upload_to='projets/pdf/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projets/images/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('est_valide', models.BooleanField(default=False)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.filiere')),
            ],
        ),
    ]
